def hook_tool_catalog(config_json: str) -> str: ...

class HarnessSession:
    @staticmethod
    def create(config_json: str, initial_history_json: str) -> HarnessSession: ...
    @staticmethod
    def restore(
        config_json: str, checkpoint_json: str, resume_input_id: int = 0
    ) -> HarnessSession: ...
    def apply(self, input_json: str) -> str: ...
    def inspect(self) -> str: ...
    def checkpoint(self) -> str: ...
    def close(self) -> None: ...
